version: '3.1'
services:
  #app-pm:
   #   build: ./webhooks
    #  image: keymetrics/pm2:latest-alpine
     # ports:
      #  - "8080:8080"
  nginx:
    restart: always
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./docs/.vuepress/dist:/var/www/html/
